# Generated by Django 4.2.8 on 2024-01-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='phone_number',
            field=models.IntegerField(default='0700000000'),
        ),
    ]
