# Generated by Django 4.2.8 on 2024-01-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartorder_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('delivered', 'Delivered'), ('book', 'Booked')], default='processing', max_length=30),
        ),
    ]
